spring:
  application:
    name: service-discovery

server:
  port: ${EUREKA_SERVER_PORT:8761}

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
  client:
    registerWithEureka: ${REGISTER_WITH_EUREKA:false}
    fetchRegistry: ${FETCH_REGISTRY:false}
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka}