spring:
  application:
    name: song-service

  datasource:
    url: ${SONG_DB_URL:jdbc:postgresql://localhost:5433/song_db}
    username: ${SONG_DB_USER:postgres}
    password: ${SONG_DB_PASSWORD:postgres}
    driver-class-name: ${SONG_DB_DRIVER:org.postgresql.Driver}

server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP}:true
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka}
    registry-fetch-interval-seconds: ${FETCH_INTERVAL:5}