spring:
  application:
    name: song-service

  datasource:
    url: ${SONG_DB_URL:jdbc:postgresql://localhost:5433/song_db}
    username: ${SONG_DB_USER:postgres}
    password: ${SONG_DB_PASSWORD:postgres}
    driver-class-name: ${SONG_DB_DRIVER:org.postgresql.Driver}

server:
  port: ${SONG_SERVICE_PORTS:8082}

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    non-secure-port: ${SONG_SERVICE_PORT:8082}
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka}
    registry-fetch-interval-seconds: ${FETCH_INTERVAL:5}