spring:
  application:
    name: song-service

  datasource:
    url: ${SONG_DB_URL:jdbc:postgresql://localhost:5433/song_db}
    username: ${SONG_DB_USER:postgres}
    password: ${SONG_DB_PASSWORD:postgres}
    driver-class-name: ${SONG_DB_DRIVER:org.postgresql.Driver}

server:
  port: ${SONG_SERVICE_PORT:8081}