spring:
  application:
    name: resource-service

  datasource:
    url: ${RESOURCE_DB_URL:jdbc:postgresql://localhost:5432/resource_db}
    username: ${RESOURCE_DB_USER:postgres}
    password: ${RESOURCE_DB_PASSWORD:postgres}
    driver-class-name: ${RESOURCE_DB_DRIVER:org.postgresql.Driver}

server:
  port: ${RESOURCE_SERVICE_PORT:8080}

song-service:
  url: ${SONG_SERVICE_URL:http://localhost:8081/songs}