spring:
  application:
    name: resource-service

  datasource:
    url: ${RESOURCE_DB_URL:jdbc:postgresql://localhost:5432/resource_db}
    username: ${RESOURCE_DB_USER:postgres}
    password: ${RESOURCE_DB_PASSWORD:postgres}
    driver-class-name: ${RESOURCE_DB_DRIVER:org.postgresql.Driver}

server:
  port: ${RESOURCE_SERVICE_PORT:8081}

song-service:
  url: ${SONG_SERVICE_URL:http://song-service/songs}

eureka:
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP}:true
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka}
    registry-fetch-interval-seconds: ${FETCH_INTERVAL:5}